### PR TITLE
Bump contract solidity version

### PR DESCRIPTION
**Pull request by zhilongliu**
This error was being thrown:

```
, SyntaxError: Source file requires different compiler version (current compiler is 0.4.24+commit.e67f0147.Emscripten.clang - note that nightly builds are considered to be strictly less than the released version
pragma solidity 0.4.23;
```

due to we're using the latest 0.4.24 version.

Fixes: fe170b058622 (Bump contract solidity version)

Signed-off-by: Zhilong Liu <zhilong.liu1028@gmail.com>

--- ---
As alternative method, I also recommend the following changings:

pragma solidity 0.4.23 ==> pragma solidity ^0.4.23

### CODE REVIEW

**Comment by zhilongliu** [comment]
Hi,
I have checked the CI console output, the solidity compiler version is 0.4.23 in the CI testing environment, thus it complains the "pragma solidity 0.4.24" and aborts the whole testing.
I would keep waiting for your response to discuss, I have provided 2 methods in my commit-comments.

Best regards,
Zhilong

**Comment by zhilongliu** [comment]
@wanderingstan , @tyleryasaka ,  @micahalcorn, @nick

Would you have a look at this?

Thanks,
Zhilong

**Comment by wanderingstan** [comment]
Thanks @zhilongliu !

We pegged solidity to specific versions in https://github.com/OriginProtocol/origin-js/commit/fdfa0fb9d59b83e7f88fcf779cb3c79ea32497dc. It is said that limiting to a specific version increases security. 

The issue may be truffle. our `package.json` says `"truffle": "^4.1.8"` ([link](https://github.com/OriginProtocol/origin-js/blob/develop/package.json#L69)), which used `solc` 0.4.23. But truffle moved to solc 0.4.24 in [version 4.1.9](https://github.com/trufflesuite/truffle/issues/950#issuecomment-390749799) 

The `^` in our truffle version means travis would pick up truffle 4.1.9, and put us on solc 0.4.24. 

I agree that we should just move all our solc files to `0.4.24` as long as tests are passing.

**Comment by zhilongliu** [comment]
thanks for your swift response, and thanks for changing the pr to develop branch.

Best regards,
Zhilong

**Comment by zhilongliu** [comment]
hi @tyleryasaka @wanderingstan 

I update 1 new commit in my fork,

commit 960d8bb7daac
("reject directly if truffle migrate failed")
    
I recommend to execute reject() if truffle compile-all got failure,
it's not worth to continue.

Any suggestions is welcome. 

Thanks,
Zhilong

**Comment by zhilongliu** [comment]
@tyleryasaka 
yes, the commit: 19a921af0ba2 (Bump contract solidity version) in my fork is dependent by truffle/solc compiler version(solc need  == 0.4.24)， thus the CI would complain and abort.
and for the commit: 960d8bb7daac (reject directly if truffle migrate failed) in my fork, this commit isn't dependent the compiler version, it just fixed the code logic.

Thanks,
Zhilong

**Comment by zhilongliu** [comment]
@tyleryasaka I have checked via to 'git blame ./scripts/helper/deploy-contracts.js' before I submit this commit: 960d8bb7daac (reject directly if truffle migrate failed) , it wrote by you, thus I apply for your review.

Thanks,
Zhilong

**Comment by zhilongliu** [comment]
@wanderingstan 
would you help for reviewing this commit: 960d8bb7daac ("reject directly if truffle migrate failed") in my branch?

Any suggestions is welcome.

Thanks,
Zhilong

**Comment by tyleryasaka** [comment]
Hi @zhilongliu - haven't forgotten about this, just been busy. Sorry for the delay! Hoping to look soon.

**Comment by tyleryasaka** [comment]
I fixed this here: https://github.com/OriginProtocol/origin-js/pull/419/files

Thanks!

**Pull request closed without merging**
