### PR TITLE
Source map type change

### PR DESCRIPTION
**Pull request by tomlinton**
First pull request? Read our [guide to contributing](http://docs.originprotocol.com/#contributing)

### Checklist:

- [x] Code contains relevant tests for the problem you are solving
- [x] Ensure all new and existing tests pass
- [x] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/docs)
- [x] Submit to the `develop` branch instead of `master`

### Description:

- Changed the source map type to something that should provide a better experience when setting breakpoints in Chrome. It should also be faster to generate.
- Removed some docker stuff that is no longer used.

### CODE REVIEW

**Comment by micahalcorn** [comment]
Thanks @tomlinton 🙏 Were you able to test this and get a different debugging experience? I am running this and https://github.com/OriginProtocol/origin-dapp/tree/tomlinton/webpack-config but I still can't set breakpoints in most places using Chrome and Firefox.

**Comment by tomlinton** [comment]
@micahalcorn with `inline-source-map` I had problems where I'd set a breakpoint in Chrome and it'd immediately unset. This addresses that for me. Did you experience that?

I still can't set breakpoints on every line though. Hope I didn't get your hopes up! I think because of how webpack transpiles things the original source code doesn't have a one to one line mapping with what is actually being executed in the browser. This means that not every line of the original source is breakpointable. I found I could always get a breakpoint when I needed it though, because there should be some line that is reasonably close. I didn't test it too extensively though.

There are other kinds of source maps we could try here. I ran across a handy graphic of the breakpoint support for each source map type, but I can't seem to find it again.

**Comment by micahalcorn** [comment]
@tomlinton in my experience it's not so much that the breakpoint unsets but that it skips down to whatever line is mapped. I haven't noticed any improvement on that front, but I'm not consistently trying to set breakpoints in the exact same places.

Yeah, I had tried `eval-source-map`, which looked like it might be the most debug-friendly, but it runs into an inability to use `require`. 😕

**Comment by tomlinton** [comment]
That's a shame, back to the drawing board on this then. :cry: We could still merge this PR though as the new source map should be faster to generate.

**Pull request merged**
