### PR TITLE
Ignore notifications that include invalid offers

### PR DESCRIPTION
**Pull request by tyleryasaka**
### Checklist:

- [x] Code contains relevant tests for the problem you are solving
- [x] Ensure all new and existing tests pass
- [x] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/docs)

### Description:

See linked issue below. This prevents invalid offers from causing the `getNotifications` method to crash.

Resolves https://github.com/OriginProtocol/origin-js/issues/558

### CODE REVIEW

**Comment by franckc** [comment]
Sweet. Thanks for working on this !

Any chance we can add a unit test for this ?

**Comment by tyleryasaka** [comment]
Dammit @franckc ! I knew you would say that! :unamused:

**Comment by franckc** [comment]
👅

**Comment by tyleryasaka** [comment]
Unit test ✅

**Comment by franckc** [comment]
Thanks for obliging me @tyleryasaka re unit tests ! You are so nice to me... :)

**Pull request merged**
