### PR TITLE
Validate arbitrator & affiliate

### LINKED ISSUE #541: Validate addresses of arbitrator, affiliate, messaging accounts
This is part of hardening origin-js.

At the origin-js layer, we should throw an error in the following scenarios:
 - ~set messaging account to anything else than official Origin messaging account~
 - create listing that uses non official Origin arbitrator or affiliate account
 - read a listing where arbitrator or affiliate is not official Origin account

### PR DESCRIPTION
**Pull request by tyleryasaka**
### Checklist:

- [x] Code contains relevant tests for the problem you are solving
- [x] Ensure all new and existing tests pass
- [x] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/docs)

### Description:

`arbitrator` and `affiliate` can now be passed in as config options at initialization of origin-js. Offers are automatically populated with and validated against these values.

Resolves #541

### CODE REVIEW

**Comment by micahalcorn** [comment]
I understand the reason for validating offers when they are retrieved rather than created, but shouldn't we at least require the presence of an affiliate address when the offer is created? If a DApp forgets to pass the affiliate param, it will seemingly "work" but the offer will never be found. In that case, the developer isn't a bad actor - just a naive actor.

**Comment by tyleryasaka** [comment]
@micahalcorn there's nothing to validate because we don't even accept affiliate address as a parameter. It's automatically populated, every time! 😄

**Comment by tyleryasaka** [comment]
The only way you can create an offer without an affiliate is to manually call the smart contracts yourself.

**Comment by micahalcorn** [comment]
@tyleryasaka fair point, but it will still fail if there is no environment variable set. We can worry about it later.

**Comment by tyleryasaka** [comment]
The only place the Dapp could mess up is when initializing origin-js. I suppose if you forgot the affiliate in the config that could be problematic.

A possible feature that could be added in a separate PR might throw an error if origin-js is initialized without `arbitrator` or `affiliate` options.

**Comment by micahalcorn** [comment]
Yeah, I like that.

**Comment by tyleryasaka** [comment]
For that matter, might want to also validate the presence of other necessary config options.

**Comment by tyleryasaka** [comment]
@micahalcorn I filed an issue: https://github.com/OriginProtocol/origin-js/issues/551

**Comment by micahalcorn** [comment]
Thanks @tyleryasaka 🙏 One other issue with this is that it produces errors when someone fetches all notifications. It's an unfortunate experience when someone requests notifications and they end up getting errors from offers that they didn't consciously ask for.

**Pull request merged**
