### PR TITLE
Update RELEASE.md to record deployment block #

### PR DESCRIPTION
**Pull request by ambertch**
### Checklist:

- [x] Code contains relevant tests for the problem you are solving
- [x] Ensure all new and existing tests pass
- [x] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/docs)
- [x] Submit to the `develop` branch instead of `master`

### Description:

Please explain the changes in this PR:

Update RELEASE.md with a note to record the block # contracts were deployed at. This allows us to know where in the blockchain events for a given version of the contracts occurred.

### CODE REVIEW

**Comment by micahalcorn** [comment]
@ambertch where should these be recorded?

**Comment by ambertch** [comment]
The truffle run logs containing the addresses are currently recorded in the release notes, alongside those could be a good place to store the information

**Comment by wanderingstan** [comment]
@ambertch -- Can you help me understand the motivation for this again? Is it specifically for our Indexing service, so when finds Events on the blockchain it knows what version it's dealing with? I'm okay with this, but it seems brittle. Is there no way to trace the event back to the contract that emitted it, and thus derive the version from the contract address?

**Comment by ambertch** [comment]
@wanderingstan yes that's true. The events are tagged with the source address as well: https://api-ropsten.etherscan.io/api?module=logs&action=getLogs&fromBlock=0&toBlock=latest&topic0=0xd8562534ed9a3ce564a595a66dbcc871a37cff70205ea8bc8d0276dcaa4d1009&apikey=9BG9HPBASP3X95Z5ERF6TY99AXAE1XXSME&address=0x2861f28756e14cf0733383be8aa66ba3b65f1b4e

Mainly I just thought that might be a good-to-have, the block number can be determined from the address as well (from the contract creation transaction).

**Comment by wanderingstan** [comment]
Added manually in https://github.com/OriginProtocol/origin-js/commit/4d6530a37f5b790878b82ad26ea113eb5480791d to get it on the release branch.

**Pull request closed without merging**
