### PR TITLE
Nick/affiliate whitelist2

### PR DESCRIPTION
**Pull request by nick**
First pull request? Read our [guide to contributing](http://docs.originprotocol.com/#contributing)

### Checklist:

- [x] Code contains relevant tests for the problem you are solving
- [x] Ensure all new and existing tests pass
- [ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/docs)

### Description:

- Adds new methods `addAffiliate` and `removeAffiliate` to Marketplace contract.
- Using addAffiliate with the marketplace contract address effectively disabled the whitelist such that any affiliate may be used.
- To keep consistency, you can also add an IPFS hash when adding or removing an affiliate which could contain more information about the new affiliate or why an affiliate was removed.

### CODE REVIEW

**Comment by cuongdo** [comment]
Also, this cannot merge until @tyleryasaka fixes #541. Otherwise, this will cause offer creation to fail because affiliate is not currently set by the dapp.

**Comment by tyleryasaka** [comment]
Yeah if you don't mind, for https://github.com/OriginProtocol/origin-js/pull/549 to be merged

**Comment by tyleryasaka** [comment]
Also @nick maybe look at my PR #549 ? Not sure if we need to do affiliate whitelisting at the contract level if we're doing that validation in origin-js (which is what my PR adds). best to keep complexity out of the contract, right?

**Comment by cuongdo** [comment]
pushed test fixes. apparently, our tests use a separately deployed marketplace contract. 🙏

**Comment by cuongdo** [comment]
@franckc @nick I just pushed an updated migration that whitelists the affiliate for each network, except for mainnet (I don't have that address yet). Please take a look

**Comment by cuongdo** [comment]
I was able to fully test a transaction with commission with the following additions to my DApps' `.env` file:

```
AFFILIATE_ACCOUNT=0x627306090abab3a6e1400e9345bc60c78a8bef57
ARBITRATOR_ACCOUNT=0x821aea9a577a9b44299b9c15c88cf3087f3b5544
```

The commission ends up in the AFFILIATE_ACCOUNT as expected, which is great.

So, I believe this is good to merge after @franckc gets both account variables in the various environments.

**Comment by franckc** [comment]
Sent out this [PR](https://github.com/OriginProtocol/origin-box/pull/89) to set the addresses on local, dev and staging environments.

**Pull request merged**
