### PR TITLE
Fix weird webpack loop

### PR DESCRIPTION
**Pull request by cuongdo**
### Checklist:

- [x] Code contains relevant tests for the problem you are solving
- [x] Ensure all new and existing tests pass
- [x] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/docs)

### Description:

Caused by importing of _helper.js. Don't know why.

### CODE REVIEW

**Comment by tomlinton** [comment]
I think this is caused by the [hot module reload](https://github.com/OriginProtocol/origin-js/blob/3172a45035a9489627a6e9dcc3ef5f2c396a9414/scripts/helpers/start-test-server.js#L7) used to start webpack for the test server. I removed it and everything works OK except the test server no longer displays any tests when I open it. :confused: 

See https://github.com/webpack/webpack/issues/2157

**Comment by franckc** [comment]
Interesting... Does anyone actually use the test server ? I find it really hard to use because when a test fails, it does not provide enough details as to what the failure is. I'd personally be inclined to get rid of it...

**Comment by tomlinton** [comment]
It uses a bunch of resources in `origin-box` because everything gets compiled twice so I'm all for getting rid of it. The only problem I see is that the tests are never run in a browser environment otherwise, they will only get run in a node environment which can be quite different.

**Comment by tyleryasaka** [comment]
I think we should maybe keep a standalone command/script that can start the test server, but it should not be included with `npm start`. It could be useful to run every once in a while but it doesn't seem like anyone is using it on a regular basis.

**Pull request merged**
