### PR TITLE
Token transfer sender/recipient whitelist

### PR DESCRIPTION
**Pull request by cuongdo**
### Checklist:

- [ ] Code contains relevant tests for the problem you are solving
- [x] Ensure all new and existing tests pass
- [x] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/docs)

### Description:

For a limited time, this enforces a whitelist of allowed senders and
recipients for Origin token transfers. The intent is to allow a gradual
launch and comply with regulations.

### CODE REVIEW

**Comment by cuongdo** [comment]
Currently, this only includes basic tests to demonstrate how the whitelist would work. We'd have real, JS tests if we agree on the high-level approach.

There is little actual logic. It's mainly safeguards and comments. All OpenZeppelin token tests still pass.

cc @joshfraser @matthewliu @franckc

**Comment by franckc** [comment]
Read the code. Really nice work at implementing this in a very readable and simple way. I also like that it emits events so it is very transparent what addresses are getting added/removed to the whitelist. And having the option to postpone the "doomsday clock" is nice to :)

Overall I like this approach. It is very easy to reason about and I don't think it would cause an issue from an auditing or community perspective. +1 with moving forward in this direction.

**Comment by joshfraser** [comment]
+1 

Thanks for the quick turnaround on this @cuongdo. Agreed that this looks like a clean and straightforward approach.

**Comment by cuongdo** [comment]
Thanks for the reviews everyone. Merging without demo test code. Tests are tracked as part of #372.

**Pull request merged**
