### PR TITLE
Allow sellers to initiate disputes

### PR DESCRIPTION
**Pull request by micahalcorn**
### Checklist:

- [ ] ~Code contains relevant tests for the problem you are solving~
- [x] Ensure all new and existing tests pass
- [ ] ~Update any relevant READMEs and [docs](https://github.com/OriginProtocol/docs)~

### Description:

This allows the seller to initiate a dispute during the `Accepted` stage as described [here](https://github.com/OriginProtocol/origin-js/issues/365#issuecomment-418532841).

### CODE REVIEW

**Comment by micahalcorn** [comment]
@cuongdo sorry, I didn't think about this. Are we actually planning to deploy/ship both v00 and v01 if they are identical?

**Comment by nick** [comment]
I think the plan is to only deploy v01. The reason there is v00 and v01 right now is so we can demonstrate and verify upgradability... ie that deploying a new contract won't have any unintended side effects in the dapp.

@micahalcorn can you make the same change to v01?

**Comment by micahalcorn** [comment]
Sure thing 👍 Should I revert the change to v00 or leave it?

**Comment by nick** [comment]
I think we agreed to only make changes in v01 going forward, so revert v00 yea

**Pull request merged**
