### PR TITLE
fix for issue #484 on ipfs hosted key leaking

### PR DESCRIPTION
**Pull request by crazybuster**
First pull request? Read our [guide to contributing](http://docs.originprotocol.com/#contributing)

### Checklist:

- [ ] Code contains relevant tests for the problem you are solving
- [X] Ensure all new and existing tests pass
- [ ] Update any relevant READMEs and [docs](https://github.com/OriginProtocol/docs)

### Description:

Please explain the changes in this PR:

This fixes the issue where messaging keys might be leaked over to other dapps in a ipfs hosted domain. Current implementation will lock the messaging keys to our dapp, or the dapp have to enable messaging in a root sub directory.

### CODE REVIEW

**Comment by DanielVF** [comment]
This breaks commit breaks Origin running under node, because node does not have a `location` variable. https://github.com/OriginProtocol/origin-js/blob/b58a97a836496a9acd3542f34eed3109b2e1301d/src/resources/messaging.js#L145

The tests still pass because the tests do not create a `Messaging` object, nor do they create an `Origin` object that creates a `Messaging` object.

**Comment by franckc** [comment]
Good catch @DanielVF - Do we anticipate we would we'll need in the future to run Messaging on node vs in-browser ? I'm not clear for what use case ? Are you thinking for writing like a customer service bot for example ?

**Comment by micahalcorn** [comment]
@franckc @DanielVF I should have caught this because origin-js will need to be able to run in the mobile app and we generally want developers to be able to import it anywhere.

**Comment by franckc** [comment]
But doesn't cookieStorage require to run in browser ? It refers to "document" - will that be available in the mobile app ?

**Comment by DanielVF** [comment]
@micahalcorn We just need to have even a simple test case that we can successfully call the messaging constructor from the tests. With no tests, I'd not expect anyone to catch it.

@franckc cookieStorage is acting like a localstorage. We just need something with that same interface that runs in node, and use it as required.

**Pull request merged**
