### PR TITLE
Reorganizing

### PR DESCRIPTION
**Pull request by tyleryasaka**
Adapters, resolvers, stores, schemas... Things are getting confusing. 😕 

Wanted to reorganize and rename some things to make them easier to understand. I also began documenting this structure.

The basic idea here is that a lot of the complex logic is now grouped under `ethereumInterface` or `ipfsInterface`. It makes it easier to follow the complexity if we can understand which parts are dealing with IPFS and which parts are dealing with the Ethereum blockchain.

Feedback welcome.

### CODE REVIEW

**Comment by tyleryasaka** [comment]
It's all just moving/renaming/splitting files. No logic changes. We have excellent test coverage for everything as well.

I think we will (hopefully) have a lot of people looking at the code right after the release and having things organized will help a lot of people and help us put our best foot forward.

My 2 cents is that it's very low risk and totally worth it. 🤷‍♂️

**Comment by franckc** [comment]
- Looking at the changes there is no logic change, just moving chunks of codes in various files...
- All the unit tests are passing. 
=> I'd be ok with getting this in.

@wanderingstan do you feel strongly against merging this ?

**Comment by wanderingstan** [comment]
I wasn't as familiar with the "old" structure anyway, so will trust that this isn't logic changes!

A minor nitpic would be the name `ethereumInterface`. We don't use "ethereum" as a specifier in our other docs and comments, usually "contract" as in our `/contracts` directory. Thus I'd prefer either `contractInterface` or maybe `ethInterface`.

**Comment by micahalcorn** [comment]
I'm fine with it as long as I can report broken things to you @tyleryasaka 🙈

**Comment by tyleryasaka** [comment]
You got it @micahalcorn 👊

**Comment by tyleryasaka** [comment]
🙏

**Comment by cuongdo** [comment]
Looks good! Our tests should minimize the chances of errors, especially since you're not changing the external APIs for the resources.

**Pull request merged**
